name: fetii_chat_env
channels:
  - conda-forge
  - snowflake
dependencies:
  - python=3.11
  - streamlit
  - requests
  - pandas
  - pip
  - pip:
    - snowflake-snowpark-python[pandas]==1.11.1
    - snowflake-connector-python==3.6.0
