name: fetii_chat_env
channels:
  - conda-forge
  - snowflake
dependencies:
  - python>=3.8,<3.13
  - streamlit
  - requests
  - pandas
  - pip
  - pip:
    - snowflake-snowpark-python[pandas]>=1.27.0
    - snowflake-connector-python>=3.6.0
